### ISSUE TITLE
Logo for TidierIteration

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/TidierIteration.jl#1]
Putting in the @pdimens bat signal 🦇

**Comment by pdimens** [comment]
Here's a first draft
![image](https://github.com/TidierOrg/TidierIteration.jl/assets/19176506/3d685831-66e5-4533-8698-3489e8d07f0f)

**Comment by kdpsingh** [comment]
@pdimens, as always, this is phenomenal!

@vituri, thoughts? Feel free to give feedback on this. Since this package is your baby, you have the final say on the logo.😊

**Comment by pdimens** [comment]
Idk how serious y'all were with having cat themes
![image](https://github.com/TidierOrg/TidierIteration.jl/assets/19176506/6639504e-93e4-4477-a3a0-9c16f73bc1bf)

**Comment by kdpsingh** [comment]
😂 -- well, it would pay homage to purrr... I'm down for either but will let others weigh in.

**Comment by pdimens** [comment]
Purrsonally, I prefer it w/o. It's very tidy and clean without the cat

**Comment by pdimens** [comment]
slight update to add some visual interest
![image](https://github.com/TidierOrg/TidierIteration.jl/assets/19176506/482ce862-b9b4-4614-aa69-75155c7bd39a)

**Comment by rdboyes** [comment]
I kind of like the cat as a nod to purrr - but without is cleaner

**Comment by vituri** [comment]
Thanks a lot, @pdimens ! Now it looks like the logo is more well-done than the package itself!

Both approachs (with or without the cat) look very nice! The allusion to the purrr package is a nice touch about its origin, but soon our packages will be used by people who don't know the tidyverse and probably won't know the reference. (well, what is "purrr" about? "purrre" functions? I don't know). So choose the one you like the most, I am happy with any choice!
